distro: trusty
sudo: required

language: go
go:
  - master

install:
  - sudo apt install libsdl2{,-mixer,-image,-ttf,-gfx}-dev
  - go get github.com/golang/dep/cmd/dep
  - dep ensure

script: go test ./chip8